series: Basic OpenGL with GLFW
title: 2D Spot Lighting
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Apply spot lighting to sprites.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: 2D Point Lighting